### PR TITLE
Init

### PR DESCRIPTION
**Pull request by did-g**
Hi,

Should fix https://github.com/seandepagnier/weather_routing_pi/issues/229 issue, and partial fix for https://github.com/seandepagnier/weather_routing_pi/issues/241

Regards
Didier

### CODE REVIEW

**Comment by rgleason** [comment]
I tested this with current version of wxRoute and Grib.
1. When I disable Climatology, I cannot disable it in the WxRte Plugin as the dropdown is frozen, however if there is enough grib data the plugin will still operate. 

Should there be a checker to see if Climatology is "enabled" and if it is "Disabled" then perhaps the WxRte Configuration > Climatology [dropdown choice] should have an X through it?  Or something visual like a red X next to it to signal that Climatology Plugin is not available?

2. When I enable Climatology,  The data is checked. Then in WxRte Config I turn off Grib and with Climatology set to "Most Likely",  start to Compute and the isochrones are all run using Climatology data.  This is working well.  I don't need to have the Climatology menu open or even have the Wind Roses showing.

3. With Grib_pi enabled, as long as I have made the right start settings etc, I don't need to have the Grib pi Menu open.  The optimal routing will still run.

**Comment by did-g** [comment]
In my understanding greying (disabling) Climatology selection list **is** the visual signal, it's done explicitly WR after noticing climatology is disabled/not there.
 Adding a big X is not easy, the other options are:
- keeping it on and show a dialog box until user select 'disable' in the list, same as draw plugin.
- hide the whole climatology stuff.

**Comment by rgleason** [comment]
Did-g, 
I had not noticed that the Climatology  drop down selection  got greyed.
I think it is because this button is slightly grey anyway, then it gets a little greyer.
I don't think the difference is enough for most of us users.
I agree about X's, perhaps there a simple way to darken the dropdown so that you can barely see the words.  That should be enough of a signal that it is not working or enabled.
If one were to hover over that area a message could show "Climatology is not enabled."? perhaps?

Hiding it when it is not enabled would also work.

**Comment by rgleason** [comment]
I added an issue #70  so this could be merged and closed.

**Pull request merged**
