### PR TITLE
New PR for Win wxWidgets 3.1.2 & opencpn.lib for 4.99mui

### PR DESCRIPTION
**Pull request by rgleason**
Pavel says some file needs to be removed for appveyor to work.  Trying to determine which file needs to be removed.

### CODE REVIEW

**Comment by nohal** [comment]
Rick...
You still need to delete line 36 (`  - cd ..`)

**Comment by rgleason** [comment]
The appveyor report states:

> make -T v141_xp ..
> CMake Error: The source directory "C:/project" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI

My local source directory for the project is "C:\Users\Frederick\Documents\GitHub\climatology_pi"
that is where CMakeLists.txt resides.   Should I use that path instead?

**Comment by nohal** [comment]
Delete line 36.

**Comment by nohal** [comment]
Now you have broken it completely, go back and only delete line 36 that has nothing to do there.

**Pull request closed without merging**
