### PR TITLE
A few chages needed to successfully build and package the latest code with the latest cmake

### PR DESCRIPTION
**Pull request by nohal**

### CODE REVIEW

**Comment by seandepagnier** [comment]
I will merge soon (internet cafe blocks using github site)

**Comment by rgleason** [comment]
Do I need to run it again to give you exact message?

**Comment by rgleason** [comment]
Github has a dns injection problem i think. Someone shiuld check it.

**Comment by seandepagnier** [comment]
no, it was the ssl certificate from github on the computers here that
have very old software..

I got wifi on the boat but it's slow, so I should be able to merge stuff now.

**Comment by rgleason** [comment]
Sean,
when I comment out cmake/PluginConfigure.cmake
this line that I added
  # CMAKE_POLICY(SET CMP0012 NEW)

C:\Data-Dart\Up-Soft\Navigation\o-plugin\climatology_pi\build>cmake ..
-- *** Staging to build climatology_pi ***
-- Found OpenGL...
--     Lib: glu32opengl32
--     Include:
-- Install Prefix: C:/Program Files (x86)/climatology_pi
CMake Warning (dev) at cmake/PluginInstall.cmake:78 (IF):
  given arguments:

    "TRUE" "AND" "EXISTS" "C:/Data-Dart/Up-Soft/Navigation/o-plugin/climatology_
pi/data"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:71 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Data-Dart/Up-Soft/Navigation/o-plugin/cl
imatology_pi/build

C:\Data-Dart\Up-Soft\Navigation\o-plugin\climatology_pi\build>

**Comment by rgleason** [comment]
Will this build with the data on Windows with cmake?

**Comment by seandepagnier** [comment]
It should

**Pull request merged**
