### PR TITLE
Mingw32

### PR DESCRIPTION
**Pull request by did-g**
Hi,
Trivial cleanup  for compiling climatology inside O source tree and with mingw (mxe)
e
Regards
Didier

BTW
It seems that some SF data are corrupted or they changed their download page.

### CODE REVIEW

**Comment by seandepagnier** [comment]
Sorry, I have trouble merging because I don't build for either type of windows.  I'm afraid this will break t he vc build.

**Comment by did-g** [comment]
Hi,
Update with O v5.0 naming scheme. 

AFAIK this version compile:
- on linux wx.3.0.4 and OSX wx 3.1.2 (you could enable travis build on your project)
https://travis-ci.org/did-g/climatology_pi/builds/497507094

- Visual studio 2017 with wx 3.1.2 Appveyor.
- locally linux and mingw wx 3.1.2 64bits with mxe, inside or outside O tree.

Regards
Didier

**Comment by rgleason** [comment]
Did-g,  Thank you!  Does this PR make Climatology now work better in mui4.99.1408 and so that we can use it with Wx_routing?

**Comment by rgleason** [comment]
I downloaded the above appveyor compile for Windows Ov4.99 and tested.
Climatology loads into Opencpn and can be enabled, however when changing preferences (month, wind, current, all check, etc) it crashes O, even in single canvas mode.

See Issues  https://github.com/seandepagnier/climatology_pi/issues

**Comment by rgleason** [comment]
I tried Climatology from the latest Appveyor https://ci.appveyor.com/project/seandepagnier/climatology-pi/builds/22616526/artifacts

1. Installing over the old climatology and using the remaining database that was downloaded from sourceforge.  
2. With the new progressbars showing it hung up on current02.
3. Then I uninstalled climatology and removed the Data directory and reinstalled.
4.. Climatology accessed sourceforge for 37 files.  Then started loading the db and hung at current02.
5. The cancel X does not work on the progress bar, but that is ok I just closed opencpn. Also I am able to bring up preferences with the progress bar still running.  I just closed Opencpn
6. Is it a corrupted db download? 
7. Downloading now from https://sourceforge.net/projects/opencpnplugins/files/climatology_pi/CL-DATA-1.0.tar.xz
8. The old Data folder that is failing has 39 files 9.30mb.  Deleted. They were gz files.
9. Install CL-DATA-1.0.tar.xz and extract completely to 43 files 42mb, one file is html, two files look like duplicates of extracted files  sealevelpressure.gz  and seatemperature.gz.   There are two files sealevelpressure and seatemperature.  (I may delete these 2 gz files.)
10. It loaded all the data it appears. and I am getting numbers in the both displays for Wind. I don't have it configured properly yet and will report back.
11. The Wind Rose does not show. I have settings of 125 & 60 with Enable checked and the opacity set to the right.  See pic.
12. When I check the Wind box in the first menu many large numbers  show, so the dislay graphics are working in the plugin. See pic.

**Regarding Data Download from SourceForge.**
Unfortunately I am finding this repository infrequent and unreliable, both during appveyor compiling (forcing me to make some small change, commit, push, make a PR - it is a PITA) I believe the files are either corrupted at the download location where ever it is or the response latency of the sourceforge server or mirrors is so bad that the data gets corrupted.

It is a bad idea to force users to hand download the CL-Data file. I believe Opencpn's own server should be used at navnux.org as it is much more reliable.

**Comment by did-g** [comment]
One big issue with sourceforge is that sometime downloads are redirect to a
proxy web page, with no error....

Rick:
If you have an appveyor account and enable your fork you can recompile
yours branches without pushing a new change or making a PR.
Very helpful for these transient errors.

Could you try PR 55
https://ci.appveyor.com/project/seandepagnier/climatology-pi/builds/22637481/artifacts

**Pull request merged**
